doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'

        types:
            experience_id: App\Catalog\Infrastructure\Doctrine\Type\ExperienceIdType
            session_id: App\Catalog\Infrastructure\Doctrine\Type\SessionIdType
            provider_id: App\Catalog\Infrastructure\Doctrine\Type\ProviderIdType
            reservation_id: App\Booking\Infrastructure\Doctrine\Type\ReservationIdType
            user_id: App\Booking\Infrastructure\Doctrine\Type\UserIdType
            money_type: App\Shared\Infrastructure\Doctrine\Type\MoneyType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Shared:
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Shared\Domain\ValueObject'
                is_bundle: false
            Catalog:
                type: xml
                dir: '%kernel.project_dir%/src/Catalog/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Catalog\Domain\Model'
                is_bundle: false
            Booking:
                type: xml
                dir: '%kernel.project_dir%/src/Booking/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Booking\Domain\Model'
                is_bundle: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
