services:
    - type: web
      name: palacin-booking-api
      env: docker
      dockerfilePath: ./render/Dockerfile
      dockerContext: .
      plan: free
      healthCheckPath: /api
      envVars:
        - key: APP_ENV
          value: prod
        - key: APP_SECRET
          generateValue: true
        - key: APP_SHARE_DIR
          value: var/share
        - key: DEFAULT_URI
          value: https://palacin-booking-api.onrender.com
        - key: MAILER_DSN
          value: null://null
        - key: DATABASE_URL
          sync: false